name: Jest Tests

on:
    push:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: '20.x'

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@v1.10.0
              with:
                  mongodb-version: '7.0.2'
                  mongodb-username: 'admin'
                  mongodb-password: 'admin'

            - name: Change directory
              run: cd server

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
              env:
                  MONGODB_URI: mongodb://admin:admin@localhost:27017/parker?authSource=admin
